# Generated by Django 3.1.7 on 2021-03-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_year'),
        ('cars', '0002_car_price'),
    ]

    operations = [
    ]
